name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        rid:
          - win-x64
          - win-x86
          - win-arm
          - win-arm64
          - linux-x64
          - linux-musl-x64
          - linux-arm
          - linux-arm64
          - osx-x64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -r ${{ matrix.rid }}
    - name: Publish
      run: dotnet publish -o eping --no-build -r ${{ matrix.rid }}
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.rid }}
        path: eping
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
